### ISSUE TITLE
AttributeError: 'RevAiAPIClient' object has no attribute 'send_job_local_file'

### ISSUE THREAD

**Issue by danielmlow** [revdotcom/revai-python-sdk#31]
When running:
```
client = apiclient.RevAiAPIClient(config.revai_access_token)
job = client.submit_job_local_file(file)
```
I get this error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rev_ai/apiclient.py", line 135, in submit_job_local_file
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.rev.ai/speechtotext/v1/jobs
```

**Comment by kbridbur** [comment]
Hey @danielmlow, thanks for bringing this to our attention! There was previously an issue with submitting from local file. I believe it should be fixed now. Please try again and close this issue if it works :). If not feel free to post here again or email me at kyle@rev.com

I'm also curious about the title of the issue. Is there somewhere that we refer to `submit_job_local_file` as `send_job_local_file`? If so please let me know where and I'll fix it ASAP
