### ISSUE TITLE
Example Scripts Throw SSL Error

### ISSUE THREAD

**Issue by nelsonapollolee** [revdotcom/revai-python-sdk#50]
Hi,

If you take "generator_streaming_example.py" and run it with a valid access token, it throws an exception on line 42:

`response_generator = streamclient.start(MEDIA_GENERATOR)
`

with the below error trace.

Any ideas? I get the same error when running "microphone_streaming_example.py" with the same command (line 102).

> /Users/nlee/PycharmProjects/AudioRead/env/bin/python3.7 /Users/nlee/PycharmProjects/AudioRead/revai-python-sdk-develop/examples/generator_streaming_example.py
Traceback (most recent call last):
  File "/Users/nlee/PycharmProjects/AudioRead/revai-python-sdk-develop/examples/generator_streaming_example.py", line 42, in <module>
    response_generator = streamclient.start(MEDIA_GENERATOR)
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/rev_ai/streamingclient.py", line 94, in start
    self.on_error(e)
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/rev_ai/streamingclient.py", line 16, in on_error
    raise error
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/rev_ai/streamingclient.py", line 92, in start
    self.client.connect(url)
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/websocket/_http.py", line 260, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Users/nlee/PycharmProjects/AudioRead/env/lib/python3.7/site-packages/websocket/_http.py", line 239, in _wrap_sni_socket
    server_hostname=hostname,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

Process finished with exit code 1

**Comment by nelsonapollolee** [comment]
Looks like the non-streaming APIs work. A configuration for the WebSocket server?

**Comment by amikofalvy** [comment]
It appears that your local python installation configuration is not complete.

A quick search for the error `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)` shows a potential solution which has solved the misconfiguration when we've experienced the same.

https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

**Comment by amikofalvy** [comment]
This issue has been posted and solved previously in https://github.com/revdotcom/revai-python-sdk/issues/37
